### PR TITLE
PR_REPLY_TEMPLATE - More beautification for regular readers

### PR DESCRIPTION
**Pull request by totten**
Overview
---------

This is a follow-up to #8. It retains the content and tone, but it improves the layout for folks who read regularly. 

You can see a rendering of this content at https://github.com/totten/githubtest/issues/14.

Changes
---------

* Split into collapsible sections (`<details>`)
    * A wall of text is OK on your first PR, but it gets old if you read multiple PRs.
* Combine `PR_REPLY_TEMPLATE` and `PR_NEW_REPLY_TEMPLATE` into one.
    * Since the intro is collapsible, it's OK to always include the links for `contributor-key.yml` and `CONTRIBUTING.md`. This should be better for 2nd-time/3rd-time contributors (*you can re-find links*) -- and also for bot-developers (*less functionality to consider*)
* Add more icons (emojis) to distinguish links

(*There are some more comments about these in the commit-messages.*)

### CODE REVIEW

**Comment by mlutfy** [comment]
Can you collapse both sections? It will be more obvious that they are uncollapsible. Otherwise I think the "Intro for developers" is easy to overlook, since the eye immediately goes on the second section.

**Comment by colemanw** [comment]
I'm curious to know if we no longer have two templates due to technical limitations? If I'd known how, I would have written two versions of the blurb (or maybe 3) based on the user role of the author.

**Comment by mlutfy** [comment]
@colemanw In theory it does check if it's a first-time-ever-PR, and replies `PR_NEW_REPLY_TEMPLATE`

Although personally I find all of the links handy. I think the target audience should be folks who PR every 1-2 months, not 1-2 days.

**Comment by totten** [comment]
> (@colemanw) I'm curious to know if we no longer have two templates due to technical limitations?

Not really sure either way. It might. Regardless, it's a bit annoying to test... and I think the unified msg is better for the person contributes 1 PR every 1-2 months.

> (@mlutfy) Can you collapse both sections? It will be more obvious that they are uncollapsible...

Yeah, I'm OK with collapsing both. (Upshot: At some point, we might squeeze in additional links for https://test.civicrm.org/job/CiviCRM-Manual/ and https://test.civicrm.org/job/CiviCRM-Manual-Test/.  If the section is collapsed by default, then I think it will still feel clean enough.)

**Comment by mlutfy** [comment]
Deployed to prod :sunflower:

**Pull request merged**
